apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elkpvc
  namespace: cdielk
spec:
  storageClassName: elksc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
